language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
script:
  - python3 -m pytest -v tests/test_dice.py
deploy: &heroku
  provider: heroku
  app: ci-homework-production-sesp-13
  api_key: $HEROKU_AUTH_TOKEN
  on:
  -branch: main

