language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
script:
  - python3 -m pytest -v tests/test_dice.py
deploy: &heroku
  provider: heroku
  api_key: 
    secure: AWWh88bIoNxCt8EoflY4LaNbA9IXgqdIP2J8DOwhSSc3sVk/5u2vJSjK4XCGTSH0bV7EJNb12lg9Si6cdTB8LtXk2mxQzPOdduqAicNVjIg1lAciXfdi8gIQdR5I6B67XRadrS6ns++RmnEwvjfzQiC/dMUwIiSNIkbBqSw5gYC+I7WtpyBhuOXLlW060fgSGh8wx68aoPff1Ds6XpDTUrwDVtDXuaW1oCWpySTmWBp67WbIo8/pTfi5tIA/w6NCxz67CfHSoy7u6xAFha6t3e9zOs5S8MNiy7V0m16LfbluU7EWzMzxR5EaqOKQm5T7V8ZKOKO9uboaW32E5Vd84mN0GDDW1z+e9JOjG5d5zD0VuGo3cv+6jP0BbboNelPY0SqeA5E2p7RbAwCUtH5+6ySapJXKtHxPeVUnQ8PwAk3FMV9v/lRz63JugRXh/8mSt9wYoB3iAwVdyxOsqqkhDyGXY5lR99jM0Jp7t7zZftHit2L581uJc6Cnx92kfr1kOKN1VJ4lUxhItNiSgpZ98qVo5Oy95xqhQ/xOMoEzerT0UHShH4xKaWIarDvv3im7lpwXOp+ZfHkauNqnnG/ysu1dBrizwzEChNeiaY+a6PBW/Idbtx8kWFagJQ6VYhwWSRVAGLqLFjUzwOBSZCig89XUi7uacEUasI8/NbRsc+o=
  app: 
    main: ci-homework-staging-sesp-13
    production: ci-homework-production-sesp-13

